### ISSUE TITLE
Add cuttlefish to current components

### ISSUE THREAD

**Issue by JenMysoc** [poplus/home-poplus#109]
Cuttlefish is (according to the poplus blog) now available with hosting through Poplus. Should we add it to the list of current components? (cc @mlandauer )

**Comment by mlandauer** [comment]
Before that can happen Cuttlefish needs to be approved to be an official poplus component. I'm planning to apply for that within the next week or so and then fingers crossed that it fits the bill ;-)

**Comment by mlandauer** [comment]
Now Cuttlefish is officially a poplus component work looks to be underway on the [cuttlefish branch](https://github.com/poplus/home-poplus/tree/cuttlefish)

**Comment by jpmckinney** [comment]
i.e. https://github.com/poplus/home-poplus/pull/117 :)
