### ISSUE TITLE
Site layout not optimized for Firefox.

### ISSUE THREAD

**Issue by JenMysoc** [poplus/home-poplus#21]
![graphic](https://f.cloud.github.com/assets/4170351/2526205/00031294-b4f8-11e3-944a-0d81618305bd.jpg)
![countdown](https://f.cloud.github.com/assets/4170351/2526207/0296602e-b4f8-11e3-9d64-87b07dd2609d.jpg)

**Comment by lfalvarez** [comment]
The problem seems to be in these lines https://github.com/ciudadanointeligente/home-poplus/blob/gh-pages/css/main.css#L496-L498, and some clues of what the problem is can be found here http://css-tricks.com/image-under-text/

**Comment by martinszy** [comment]
This issue was for the old site, I think it should be closed.

**Comment by maugsbur** [comment]
Let's see if we can close #21 by mail

2014-05-30 23:31 GMT-04:00 Martín Szyszlican notifications@github.com:

**Comment by maugsbur** [comment]
...nope
