### ISSUE TITLE
Update Poplus.org homepage to reflect post-conference reality

### ISSUE THREAD

**Issue by TomSteinberg** [poplus/home-poplus#27]

**Comment by tmtmtmtm** [comment]
@TomSteinberg do you have an idea for what this should be? I've already made a few incremental smaller changes (removed the 0:00:00 countdown from this page; changed the main conference page to be past tense; removed the "How to submit a talk" stuff; updated the schedule to have names of talks linking to the write-ups; etc). Is there something else easy we should do to the homepage in advance of having the "Big Questions" write-ups (#28 + equivalents) ready to link to?

**Comment by TomSteinberg** [comment]
So I guess the new Poplus homepage will need to link to various things, including:
- About Poplus the federation - how to get involved, what's going on
- Definition of a Poplus component
- Homepages of the various components
- About Popluscon

I've asked Martin to work with you and Myf on this, starting tomorrow

**Comment by zarino** [comment]
Martin's finished a first iteration of the redesign, and it's been approved for deployment by the Poplus Comms team. I'm going to email the guys at FCI to make sure this happens, alongside the [redirections outlined here](https://github.com/ciudadanointeligente/home-poplus/issues/34).

**Comment by jpmckinney** [comment]
Done? http://poplus.org/
