### ISSUE TITLE
New poplus.org site will require some redirects

### ISSUE THREAD

**Issue by wrightmartin** [poplus/home-poplus#34]
On the redesign we've changed the page structure, so it will need a few redirects to stop broken links when it goes live
- /about.html -> /about/
- what-is-a-component.html -> /components/
- /catalogue.html -> /components/
- /popluscon_sessions.html -> /popluscon/
- /join/ -> /get-involved/

**Comment by jdgarrido** [comment]
@wrightmartin 
i have an issue with your suggest about permalinks and two links pointing the same place, is right this? 
both, /what-is-a-component and /catalogue are going to /components??

btw, recently i add the permalinks for compatibility with the new site :smile:

**Comment by TomSteinberg** [comment]
Hi Jose - that is correct, for now both these links go to the same place.

**Comment by MyfanwyNixon** [comment]
Please could we also redirect http://poplus.org/join/group.html to http://poplus.org/get-involved/? 

Apparently the former has been widely advertised on forums, etc.
