### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MyfanwyNixon** [poplus/home-poplus#37]
"The new design of the website is not using the poplus logo as it is. The "POPLUS" word is part of the logo including the font. In order to keep coherent with the t-shirts, stickers, notebooks, etc. @Zarino is it possible to correct that? I think in the rest of the sites the application of the brackets is is good, but for the main site I rather like the full logo." - notes via https://groups.google.com/d/msg/poplus/jvwDCwxodDQ/OdGkVzZzZIUJ

**Comment by zarino** [comment]
This was done a while back. Could someone close this ticket?
