### ISSUE TITLE
Design: ability to add more images to inner pages (also video?)

### ISSUE THREAD

**Issue by MyfanwyNixon** [poplus/home-poplus#39]
One of the issues that came up in the Comms meeting was that we'd like the option to add more images to inner pages of the site.

It looks like we will also have some good video content to add, so please can we include that option too?

**Comment by jdgarrido** [comment]
@MyfanwyNixon it's possible add images in the inner page, only need add the following code

[in Markdown format](http://daringfireball.net/projects/markdown/basics)

![Alt text](http://poplus.org/images/post_images/2014-02-26-save-the-date-flyer.png)

[and in HTML format](http://www.w3schools.com/html/html_images.asp)

<img src="http://poplus.org/images/post_images/2014-02-26-save-the-date-flyer.png" alt="Alt text" title="Optional title" class="some_class" />

but this one, only display one image and if you wanna display a gallery you need make this one by one to complete the gallery

i recommend just add one image and add a link where the gallery is, for example flickr or google+

in case of video, natively is not possible, but, as an image, you can add a image or screenshot of the video and add the link in this way

[![Alt text](http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)

an example:

[![Red Hot Chilli Peppers](http://img.youtube.com/vi/YlUKcNNmywk/0.jpg)](http://www.youtube.com/watch?v=YlUKcNNmywk)

also, you can use iframe, but i don't recommend
