### ISSUE TITLE
Add popluscon video to popluscon page

### ISSUE THREAD

**Issue by martinszy** [poplus/home-poplus#47]
Videos are great, lots of people like to watch them more than reading, so I think this video should be part of the site: 
https://www.youtube.com/watch?v=0WbAQlCu0zQ

This is the video about popluscon, so maybe in this page: http://poplus.org/popluscon/

Or at least, it should be embedded the post that is linked from that page, here:
https://www.mysociety.org/2014/05/09/a-federation-is-born/

Otherwise there would be no direct way to get from the site to our only video content.

**Comment by maugsbur** [comment]
I agree. The fastest way to get it there is either creating a pull request,
or posting it as a thread for the communications committee.

2014-05-30 23:38 GMT-04:00 Martín Szyszlican notifications@github.com:

**Comment by jpmckinney** [comment]
Seems to have been done. http://poplus.org/popluscon/
