### ISSUE TITLE
Changes arising from the Communications meeting

### ISSUE THREAD

**Issue by MyfanwyNixon** [poplus/home-poplus#50]
Please see https://docs.google.com/document/d/13EHvs6tm32V0wKUt07c9G-xiJerf4AGqhM23kRjUPTc/edit# for some changes to copy.

I am going to allocate these to mySociety's designers for a hopefully quick turnaround :)

**Comment by zarino** [comment]
New URL for document is: https://docs.google.com/a/mysociety.org/document/d/1Mbg-vw7fuJ6j4YKfswOdERP6zhfoD9xB2lhuJOLuwPM/edit (mySociety-only – let us know if you need access)

**Comment by zarino** [comment]
I don't have pushing rights for [ciudadanointeligente/home-poplus](https://github.com/ciudadanointeligente/home-poplus), but I've pushed my work so far into a new branch on the mysociety fork of the site: [mysociety/home-poplus/compare/new-pages-june-2014](https://github.com/mysociety/home-poplus/compare/new-pages-june-2014?expand=1)

It's mostly done. Just need to take screenshots of the web pages listed in the "examples" section, and we're done.

**Comment by MyfanwyNixon** [comment]
Thanks so much Zarino!

## 

All the best,

Myf Nixon
Marketing and Communications Manager
mySociety

Tel: 020 3287 9859
Twitter: @MySocMyf https://twitter.com/#%21/MySocMyf

mySociety blog http://www.mysociety.org/blog/
Follow mySociety on Twitter https://twitter.com/mysociety
Like mySociety on Facebook http://www.facebook.com/mySociety

**Comment by zarino** [comment]
Pull request here: https://github.com/ciudadanointeligente/home-poplus/pull/54
