### ISSUE TITLE
Broken Link on http://poplus.org/about/

### ISSUE THREAD

**Issue by ernestogimeno** [poplus/home-poplus#65]
where it says "If this sounds like something you want to be part of, please join our mailing list and send a message saying you want to be involved, and mentioning which sub-committee (or committees) you'd like to join.", the link on "send a message" pointing to http://poplus.org/join/group.html?place=topic%2Fpoplus%2F8kLpLL3d8z0%2F gives 404 error

**Comment by lfalvarez** [comment]
Hey there:
Where is this link displayed? I think that currently the about/ page is take from [about/index.md](https://github.com/poplus/home-poplus/blob/gh-pages/about/index.md)

**Comment by ernestogimeno** [comment]
well....I can't reproduce this anymore (I did a few times before reporting this issue) maybe I had an old version cached...

**Comment by lfalvarez** [comment]
may be this has to do more with removing the about.md file
