### ISSUE TITLE
Change wording on homepage

### ISSUE THREAD

**Issue by MyfanwyNixon** [poplus/home-poplus#68]
Our strapline currently reads: "Sharing technology to help civic and democratic activists… everywhere"

It has been suggested that the use of the word 'activists' might be off-putting to some groups and organisations (and funders?).

So instead I propose "Sharing technology to help civic and democratic projects… everywhere".

(could also use 'initiatives' or 'movements'; thoughts welcome)

**Comment by jpmckinney** [comment]
:+1:
