### ISSUE TITLE
Poplus.org support for different languages

### ISSUE THREAD

**Issue by zawsx** [poplus/home-poplus#85]
There is no facility I am aware of to use Poplus.org in a language different from English.
It could be based on the detection of the browser language ('HTTP_ACCEPT_LANGUAGE' in HTML) directly on the home page, so that people are welcomed in their own language. 
Someone using that language cannot always be assumed to be physically in the country where that language is most often spoken.
As this is such a common requirement, I hope we can use a popular pre-existing solution rather than write (and have to maintain ) code ourselves in perpetuity. A multi-language CMS plugin for example.

Google Translate could be used initially to auto-translate all our existing content, then a scheme created whereby a page can be marked 'validated' if someone who speaks that language says it makes sense. Maybe invited readers of the content to validate it on first visit.

Also be good to remind content creators that this is going to be translated, asking that, if they speak any other languages themselves, they provide content in that other language too.

**Comment by jpmckinney** [comment]
See #44 ?

Let's try finding volunteer translators before we consider setting up Google Translate + anonymous visitor content validation.

**Comment by zawsx** [comment]
Thanks James - I was thinking more of upvoting. Are we likely to get more
than a fraction of languages covered by explicit volunteers?
I felt that visitors might very well quickly correct an auto-translation
but many not want to sign up formally, so let's leverage the goodwill.
Anonymity is fine as long as the anonymous agree :)

Regards
Chris Setz
email  chrisN1@setzweb.com
direct _07887 49 36 58_ (normal rates but subject to change)
permanent 0709 231 5890 (approx £0.50/minute - 'free' minutes cannot be
used)

**Comment by jpmckinney** [comment]
I think targeting the top languages will be a good enough start.

Getting volunteers is a simpler technological approach. If someone has the goodwill to implement a more complex solution, we can consider it.

**Comment by zawsx** [comment]
Good idea - now you're talking my language :)

Regards
Chris Setz
email  chrisN1@setzweb.com
direct _07887 49 36 58_ (normal rates but subject to change)
permanent 0709 231 5890 (approx £0.50/minute - 'free' minutes cannot be
used)

**Comment by jpmckinney** [comment]
Moving forward with #44 We can revive alternatives once interest is expressed on the mailing list.
